name = "rakkas-worker-test"
main = "dist/server/cloudflare-workers-bundle.js"
compatibility_date = "2024-03-24"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = true

site = { bucket = "./dist/client" }


# Binding to a Durable Object
[[durable_objects.bindings]]
name = "DO_BROWSER" # DurableObject Browser
class_name = "DoBrowser"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DoBrowser"] # Array of new classes